TestAss2/TestAss2/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestAss2.Models;

namespace TestAss2.Controllers
{
    public class BlogController : Controller
    {
        BlogClient blClient = new BlogClient();
        UserClient usClient = new UserClient();
        TypeBlogClient typeBL = new TypeBlogClient();
        // GET: Blog
        public ActionResult Index()
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
            var email = dataUser.Email;
            var pwd = dataUser.Password;
            var data = blClient.GetAllLisBlog(email,pwd);
            
            ViewBag.DataUser = usClient.getAllUser();

            return View(data);
        }

        // GET: Blog/Details/5
        public ActionResult Details(int id)
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
            var email = dataUser.Email;
            var pwd = dataUser.Password;
            var data = blClient.GetBlogById(id,email,pwd);
            foreach(var item2 in usClient.getAllUser())
            {
                if(item2.ID == data.UserID)
                {
                    ViewBag.DataUser = item2.UserName;
                }    
            }
            foreach(var item3 in typeBL.getAllTypeBlog())
            {
                if(item3.ID == data.TypeBlogID)
                {
                    ViewBag.DataTypeBl = item3.TypeName;
                }
            }
            ViewBag.DataDetail = data;
            ViewBag.ContentShort = data.ContentShort;
            if(data.Status==1)
            {
                ViewBag.Status = "Hiện";
            }
            else
            {
                ViewBag.Status = "Ẩn";
            }
            ViewBag.Content = data.Content;
            return View(data);
        }

        // GET: Blog/Create
        public ActionResult Create()
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
            ViewBag.UserID = dataUser.ID;
            ViewBag.TypeBlogID = new SelectList(typeBL.getAllTypeBlog(),"ID", "TypeName");
            return View();
        }

        // POST: Blog/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Blog bl,int status)
        {
            ViewBag.TypeBlogID = new SelectList(typeBL.getAllTypeBlog(), "ID", "TypeName", bl.TypeBlogID);
            try
            {
                // TODO: Add insert logic here
                if (Session["loginSession"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
                var email = dataUser.Email;
                var pwd = dataUser.Password;
                bl.UserID = dataUser.ID;
                bl.Image = "1";
                bl.Status = status;
                blClient.StoreBlog(bl,email,pwd);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
            var email = dataUser.Email;
            var pwd = dataUser.Password;
            var data = blClient.GetBlogById(id,email,pwd);
            ViewBag.TypeBlogID = new SelectList(typeBL.getAllTypeBlog(), "ID", "TypeName",data.TypeBlogID);
            return View(data);
        }

        // POST: Blog/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, Blog bl)
        {
            ViewBag.TypeBlogID = new SelectList(typeBL.getAllTypeBlog(), "ID", "TypeName", bl.TypeBlogID);
            try
            {
                // TODO: Add update logic here
                if (Session["loginSession"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                var dataUser = usClient.CheckUser(Session["loginSession"].ToString());
                var email = dataUser.Email;
                var pwd = dataUser.Password;
                bl.Image = "1";
                bl.UserID = dataUser.ID;
                blClient.EditBlog(bl);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Blog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestAss2/TestAss2/Controllers/TypeBlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestAss2.Models;

namespace TestAss2.Controllers
{
    public class TypeBlogController : Controller
    {
        TypeBlogClient typeBlogClient;
        public TypeBlogController()
        {
            typeBlogClient = new TypeBlogClient();
        }
        // GET: TypeBlog
        public ActionResult Index()
        {
            var data = typeBlogClient.getAllTypeBlog();
            return View(data);
        }

        // GET: TypeBlog/Details/5
        public ActionResult Details(int id)
        {
            var data = typeBlogClient.getTypeBlogById(id);
            return View(data);
        }

        // GET: TypeBlog/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: TypeBlog/Create
        [HttpPost]
        public ActionResult Create(TypeBlog tp)
        {
            try
            {
                // TODO: Add insert logic here
                typeBlogClient.AddTypeBlog(tp);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TypeBlog/Edit/5
        public ActionResult Edit(int id)
        {
            var data = typeBlogClient.getTypeBlogById(id);
            return View(data);
        }

        // POST: TypeBlog/Edit/5
        [HttpPost]
        public ActionResult Edit(TypeBlog tp)
        {
            try
            {
                // TODO: Add update logic here
                typeBlogClient.EditTypeBlog(tp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TypeBlog/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TypeBlog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestAss2/TestAss2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestAss2.Models;

namespace TestAss2.Controllers
{
    public class UserController : Controller
    {
        UserClient usData;
        HomeController homeControl;
        public UserController()
        {
            usData = new UserClient();
            homeControl = new HomeController();
        }
        // GET: User
        public ActionResult Index()
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
           
                var data = usData.getAllUser();
                return View(data);
            
            
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var data = usData.getUserById(id);

            return View(data);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(User us)
        {
            try
            {
                // TODO: Add insert logic here
                if (Session["loginSession"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                usData.StoreUser(us);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["loginSession"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var data = usData.getUserById(id);
            return View(data);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, User us)
        {
            try
            {
                
                usData.EditUser1(us);
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
    }
}

TestAss2/TestAss2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["loginSession"] != null)
                    {
                        <li>@Html.ActionLink(Session["loginSession"].ToString(), "LogoutSession", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login Session", "LoginSession", "Home")</li>
                    }
                <li>@Html.ActionLink("Ql User", "Index", "User")</li>
                <li>@Html.ActionLink("Ql Blog", "Index", "Blog")</li>
                <li>@Html.ActionLink("Ql Type Blog", "Index", "TypeBlog")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestAss2/TestAss2/Views/Shared/_LayoutA.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body>
    @RenderBody()

    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/dist/js/adminlte.min.js"></script>
</body>
</html>